global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['yourdomaine.local:9090']

  - job_name: 'node1'
    static_configs:
      - targets: ['yourdomaine.local:9100']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: [yourdomaine.local:8084]