version: '3'

services:
  web:
    image: nginx:latest
    container_name: nginx-portfolio-prod-1
    restart: always
    #ports:
    #  - "80:80" 
    labels:
     - "traefik.enable=true"
     - "traefik.http.services.nginx-portfolio-prod-1.loadbalancer.server.port=80"
     - "traefik.http.routers.nginx-http.rule=Host(`nginx.srv-prod-1.yourdomaine.uk`)"
     - "traefik.http.routers.nginx-https.rule=Host(`nginx.srv-prod-1.yourdomaine.uk`)"
     - "traefik.http.routers.nginx-https.entrypoints=websecure"
     - "traefik.http.routers.nginx-http.entrypoints=web"
     - "traefik.http.routers.nginx-https.tls=true"
     - "traefik.http.routers.nginx-https.tls.certresolver=production"
     - "traefik.http.routers.nginx-https.tls.domains[0].main=nginx.srv-prod-1.yourdomaine.uk"
     - "traefik.http.routers.nginx-https.tls.domains[0].sans=*.nginx.srv-prod-1.yourdomaine.uk"
     - "traefik.http.routers.nginx-https.middlewares=middlewares-authentik@file"
    networks:
      - traefik-prod-1

networks:
  traefik-prod-1:
    external: true